version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - gocyclo
  settings:
    govet:
      enable-all: true
    gocyclo:
      min-complexity: 15
  exclusions:
    paths:
      - ^examples/
      - ^testdata/