apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://gopgbase_prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 15s

  - name: TimescaleDB
    type: postgres
    uid: timescaledb
    access: proxy
    url: gopgbase_timescaledb:5432
    database: tsdb
    user: postgres
    editable: false
    secureJsonData:
      password: secret
    jsonData:
      sslmode: disable
      postgresVersion: 1800
      timescaledb: true
